project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse
from django.conf.urls.static import static

urlpatterns = [
    path('', include('social.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('health/', lambda request: HttpResponse("OK")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path, include

from social import views, viewsets, api

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('profiles', viewsets.ProfileViewSet)

app_name = 'social'

urlpatterns = [
    # messages page
    path('', views.messages_vue, name='messages'),
    # signup page
    path('signup/', views.signup, name='signup'),
    # login page
    path('login/', views.login, name='login'),
    # logout page
    path('logout/', views.logout, name='logout'),
    # changed to documents page
    path('documents/', views.documents, name='documents'),
    # changed to editor page
    path('editor/', views.editor, name='editor'),
    # user profile edit page
    path('profile/', views.profile, name='profile'),

    # Ajax: upload new profile image
    path('uploadimage/', views.upload_image, name='uploadimage'),

    # Ajax: post a new message
    path('api/messages/', api.messages_api, name='messages api'),
    # Ajax: delete a message
    path('api/messages/<int:message_id>/', api.message_api, name='message api'),

    # Django-REST-API
    path('rest-api/', include(router.urls)),
    
    # Legal Dictionary
    path('Dictionary/', views.legal_dictionary, name="legal-dict"),
]

social/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

class Profile(models.Model):
    '''
    A Profile is simply a bit of text and/or image
    that a Member might or might not have, hence the
    OneToOne relationship in Member with null=True
    '''

    text = models.CharField(max_length=4096)
    image = models.ImageField(upload_to='profile_images')

    def __str__(self):
        return f"{self.text} ({self.member_check})"

    def to_dict(self):
        return {
            'text': self.text,
            'image': self.image.url if self.image else None,
        }

    @property
    def has_member(self):
        '''True if this profile belongs to a Member'''
        
        return hasattr(self, 'member') and self.member is not None

    @property
    def member_check(self):
        '''Either the username of the Member, or NONE'''

        return str(self.member) if self.has_member else 'NONE'


class User(AbstractUser):

    username = models.CharField(max_length=50, unique=True)
    profile = models.OneToOneField(
        to=Profile,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    following = models.ManyToManyField(
        to='self',
        blank=True,
        symmetrical=True,
        related_name='followers',
    )
    messages = models.ManyToManyField(
        to='self',
        blank=True,
        symmetrical=True,
        through='Message',
        related_name='related_to'
    )

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    def to_dict(self):
        return {
            'username': self.username,
            'profile': self.profile.to_dict() if self.profile else None,
            'messages': [ message.to_dict() for message in self.messages ]
        }

    @property
    def messages(self):
        '''Messages sent and received by this user'''

        return (self.sent.all() | self.received.all()).order_by("-time")

    def messages_with(self, view_user):
        '''Messages visible between two users'''

        # public messages that 'view_user' has received
        m1 = Message.objects.filter(recip=view_user, public=True)
        # public messages that 'view_user' has sent
        m2 = Message.objects.filter(sender=view_user, public=True)
        # messages 'user' sent 'view_user'
        m3 = Message.objects.filter(sender=self, recip=view_user)
        # messages 'view_user' sent 'user'
        m4 = Message.objects.filter(sender=view_user, recip=self)
        # union of the four query sets
        return m1.union(m2, m3, m4).order_by('-time')

    @property
    def following_count(self):
        '''Count of following'''

        return self.following.count()

    @property
    def follower_count(self):
        '''Count of followers'''
        
        return User.objects.filter(following__id=self.id).count()


class Message(models.Model):
    '''
    The Message models is the 'through' model for
    the 'message' ManyToMany relationship between Members
    '''

    sender = models.ForeignKey(
        to=User,
        related_name='sent',
        on_delete=models.CASCADE
    )
    recip = models.ForeignKey(
        to=User,
        related_name='received',
        on_delete=models.CASCADE
    )
    text = models.CharField(max_length=4096)
    public = models.BooleanField(default=True)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"From {self.sender} to {self.recip}"

    def to_dict(self):
        return {
            'id': self.id,
            'sender': self.sender.username,
            'recip': self.recip.username,
            'text': self.text,
            'public': self.public,
            'time': str(self.time)[:16], # self.time.strftime("%d/%m/%y"),
        }

social/forms.py
''' Social App Forms '''

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Row, Layout, Submit
from crispy_forms.bootstrap import FormActions

class LoginForm(forms.Form):
    '''Form for user login'''

    username = forms.CharField(
        label='Username',
        max_length=50,
        widget=forms.TextInput(attrs={'autocomplete':'username'})
    )
    password = forms.CharField(
        label='Password',
        max_length=50,
        widget=forms.PasswordInput(attrs={'autocomplete':'password'})
    )

    helper = FormHelper()
    helper.form_id = 'login-form'
    helper.layout = Layout(
        Row('username', css_class="mb-2"),
        Row('password', css_class="mb-2"),
        FormActions(
            Submit('login', 'Log in', css_class="mt-2"),
        )
    )

class SignupForm(forms.Form):
    '''Form for user signup'''

    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'autocomplete':'username',
            }
        )
    )
    password = forms.CharField(
        label='Password',
        max_length=50,
        widget=forms.PasswordInput(attrs={'autocomplete':'password'})
    )
    password_confirm = forms.CharField(
        label='Confirm Password',
        max_length=50,
        widget=forms.PasswordInput,
    )
    
    helper = FormHelper()
    helper.form_id = 'signup-form'
    helper.layout = Layout(
        Row('username', css_class='mb-2'),
        Row('password', css_class='mb-2'),
        Row('password_confirm', css_class='mb-2'),
        FormActions(
            Submit('signup', 'Sign up', css_class="btn-primary"),
            css_class='mt-3'
        )
    )

social/views.py
''' View functions '''
import json

from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
import requests

from social.models import User, Profile, Message
from social.templatetags.social_extras import display_message
from social.forms import LoginForm, SignupForm
from social.nlp import article_summarize

appname = "Legal-Ease App"

@login_required
def editor(request):

    print("---GET request caught")
    if request.method == 'POST':
        print("---POST request caught")
        text_to_summarise = request.POST ['input_text']
        summarised_text = article_summarize(text_to_summarise)

        print ("Intercepted Text:\n", text_to_summarise)
        print ("Summarised Text:\n", summarised_text)

        return render(request, 'social/pages/editor.html', {
            'page': 'editor',
            'summarised_text': summarised_text[0],
            'text_to_summarise': text_to_summarise
        })

    return render(request, 'social/pages/editor.html', { 'page': 'editor' })

def signup(request):
    form = SignupForm()

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # create a new user
            new_user = User.objects.create(username=username)
            # set user's password
            new_user.set_password(password)
            new_user.save()
            # authenticate user
            # establishes a session, will add user object as attribute
            # on request objects, for all subsequent requests until logout
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('social:messages')

    return render(request, 'social/auth/signup.html', { 'form': SignupForm })

def login(request):

    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('social:messages')

            # failed authentication
            return render(request, 'errors/error.html', {
                'error' : 'User not registered. Sign up first.'
            })

        # invalid form
        return render(request, 'social/auth/login.html', {
            'form': form
        })

    return render(request, 'social/auth/login.html', { 'form': form })



@login_required
def logout(request):
    auth.logout(request)
    return redirect('social:login')


def view_profile(request, view_username):
    '''This function is only called from'''
    
    username = request.user.username
    greeting = "Your" if username == view_username else view_username + "'s"
    try:
       user = User.objects.get(username=view_username)
    except User.DoesNotExist:
       context = {
          'error' : 'User ' + view_username + ' does not exist'
       }
       return render(request, 'social/errors/error.html', context)
    context = {
        'view_user': view_username,
        'greeting': greeting,
        'profile': user.profile,
    }
    return render(request, 'social/pages/member.html', context)

@login_required
def documents(request):
    user = request.user

    # follow new friend
    if 'add' in request.GET:
        friend_username = request.GET['add']
        try:
            friend = User.objects.get(username=friend_username)
        except User.DoesNotExist:
            raise Http404('User does not exist')
        user.following.add(friend)
        user.save()
    # unfollow a friend
    if 'remove' in request.GET:
        friend_username = request.GET['remove']
        try:
            friend = User.objects.get(username=friend_username)
        except User.DoesNotExist:
            raise Http404('User does not exist')
        user.following.remove(friend)
        user.save()
    # view user profile
    if 'view' in request.GET:
        return view_profile(request, user, request.GET['view'])
    else:
        return render(request, 'social/pages/documents.html', {
            'page': 'documents',
            'user': user,
            'documents': User.objects.exclude(username=user.username),
        })


@login_required
def profile(request):
    user = request.user

    if 'text' in request.POST and request.POST['text']:
        text = request.POST['text'][:4096]
        if user.profile:
            user.profile.text = text
            user.profile.save()
        else:
            profile = Profile(text=text)
            profile.save()
            user.profile = profile
        user.save()
    context = {
        'user': user,
        'page': 'profile',
        'profile' : user.profile,
        'session_key': request.session.session_key,
        'meta' : request.META,
    }

    return render(request, 'social/pages/profile.html', context)


@login_required
def messages_jquery(request):
    user = request.user

    if request.method == 'GET':
        # Whose messages are we viewing?
        if 'view' in request.GET:
            view = request.GET['view']
            try: 
                view_user = User.objects.get(username=view)
            except User.DoesNotExist:
                raise Http404('User does not exist')
            profile = view_user.profile
            # public messages that 'view_user' has received
            m1 = Message.objects.filter(recip=view_user,public=True)
            # public messages that 'view_user' has sent
            m2 = Message.objects.filter(sender=view_user,public=True)
            # messages 'user' sent 'view_user'
            m3 = Message.objects.filter(sender=user,recip=view_user)
            # messages 'view_user' sent 'user'
            m4 = Message.objects.filter(sender=view_user,recip=user)
            # union of the four query sets
            messages = m1.union(m2,m3,m4).order_by('-time')
        else:
            view = user.username
            profile = user.profile
            # all messages I sent
            m1 = Message.objects.filter(sender=user)
            # all messages I received
            m2 = Message.objects.filter(recip=user)
            # union of the two query sets
            messages = m1.union(m2).order_by('-time')

        context = {
            'user': user,
            'page': 'messages',
            'profile': profile,
            'view': view,
            'messages': messages,
        }

        return render(request, 'social/pages/messages-jquery.html', context)

    if request.method == 'POST':
        if 'recip' in request.POST:
            recip = request.POST['recip']
            recip_user = get_object_or_404(User, username=recip)
            text = request.POST['text'][:4095]
            pm = request.POST['pm'] == 'yes'
            message = Message.objects.create(
                sender=user,
                recip=recip_user,
                public=pm,
                time=timezone.now(),
                text=text,
            )
            return HttpResponse(display_message(message, user.username))
        else:
            raise Http404('Recip missing in POST request')


@login_required
def messages_vue(request):
    user = request.user
    view = request.GET['view'] if 'view' in request.GET else user.username

    if user.username != view:
        view_user = get_object_or_404(User, username=view)
        profile = view_user.profile
        messages = user.messages_with(view_user)
    else:
        profile = user.profile
        messages = user.messages

    vue_data = json.dumps({
        'user': user.to_dict(),
        'view': view,
        'profile': profile.to_dict() if profile else None,
        'messages': [ message.to_dict() for message in messages ],
    })

    return render(request, 'social/pages/homepage.html', {
        'vue_data': vue_data,
    })


@login_required
def upload_image(request):
    user = request.user

    if 'img_file' in request.FILES:
        image_file = request.FILES['img_file']
        if not user.profile:
            # if user doesn't have a profile yet
            # need to create a profile first
            profile = Profile(text='')
            profile.save()
            user.profile = profile
            user.save()
        user.profile.image = image_file
        user.profile.save()
        return HttpResponse(user.profile.image.url)
    else:
        raise Http404('Image file not received')


@login_required
def legal_dictionary(request): 
    if request.method == "POST":
        
        word = request.POST['word']
        print("----------------------------------")
        print(word)

        API_KEY = "ad99c07d-26d2-4bdf-acf4-b1fd34186f09"
        API = f'https://www.dictionaryapi.com/api/v3/references/collegiate/json/{word}?key={API_KEY}'
        
        response = requests.get(API)
        
        if response.status_code != 200:
            response = 'Some Error Occured, Try Again Later!'
        
        print("----------------------------------")
        print("API: ", API)
        response = response.json()[0]
        print("response:\n")
        
        print('\n')
        print(json.dumps(response, indent=4))
        print('\n')
        
        try:    
            stems = response['meta']['stems']
            print("stems: ", stems)
            print('\n')
        except Exception:
            stems = None
            print("Stems Not Printed")

        try:    
            meaning = response['def'][0]['sseq'][0]

social/templates/social/pages/documents.html
{% extends "social/base.html" %}

{% block content %}
    <div class='h3 mt-4 text-center'>
        My Documents
    </div>
    <div class='card border rounded bg-light mb-3 p-3'>
        
	</div>
{% endblock %}

social/templates/social/pages/editor.html
{% extends "social/base.html" %}

{% block content %}
    <div class='h3 mt-4 text-center'>
       Editor
        <form id="editor_form" method="POST">
            {% csrf_token %}
               <div class='container'>
                <div class="row">
                    <div class="col">
                            <textarea class="form-control" name='text' rows='1'> Untitled Document </textarea>
                    </div>
                    <div class="col">
                        <button
                            class="btn btn-primary btn-sm"
                            id="summarise" type="submit"
                            >
                                Summarise
                        </button>
                        <button
                                class="btn btn-primary btn-sm" style="border-radius: 12% / 50%;"
                                onclick="location.href='{% url 'social:documents' %}';"
                            >
                                Save to My Documents
                         </button>
                         
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="col">
                            <textarea class="form-control" name='input_text' rows='30' placeholder="Copy and paste in your text here"> {{ text_to_summarise }} </textarea>
                        </div>
                    </div>
                    <div class="col">
                        <div class='card border rounded bg-light mb-3 p-3' style='height:84vh'>
                           <p>Summarised text</p>
                           <h6 style="text-align:left">{{ summarised_text }}</h6>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
{% endblock %}

social/templates/social/pages/homepage.html
{% extends "social/base.html" %}
{% load social_extras %}
{% load static %}

{% block content %}
    <div id="app">
        <div class="thumbnail">
            <img src="static/social/fold.png" alt="" style="margin:auto; height: 90vh; width: auto">          
            <div class="caption1" style="width:auto; height:10vh;">
                <img src="static/social/laymen.gif"style=" height: 23vh" >
            </div> 
            <div class="caption">
                <h2>Written by Lawyers for lawyers</h2>
                <h6>Don't waste time! Start reading your legal documents before signing.
                Get a summarised version with key information extracted to help 
                you reduce your reading time.</h6>
                <br>
                <button
                    class="btn btn-primary btn-sm"
                    onclick="location.href='{% url 'social:editor' %}';"
                >
                    Go to Editor
                </button>
            </div>
        </div>
        <div class='container'>
            <div class="row">
                <div class="col">
                    <img src="static/social/image1.png" >
                </div>
                <div class="col">
                    <div class='h3 mt-4 text-center'>
                        Simplify and Summarise
                    </div>
                    <p class='text-center'>Copy and paste text or drag and drop documents in the 
                        editor to rewrite legal text in plain English.</p>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class='h3 mt-4 text-center'>
                        Upload and Save
                    </div>
                    <p class='text-center'>Create an account to upload legal documents and 
                        save edited versions in 'My Documents' for later use.</p>
                </div>
                <div class="col">
                    <img src="static/social/image2.png" >
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <img src="static/social/image3.png" >
                </div>
                <div class="col">
                    <div class='h3 mt-4 text-center'>
                        Define and Highlight
                    </div>
                    <p class='text-center'>Find meaning of difficult legal words, 
                        automatically highlighted by our in-built dictionary.</p>
                </div>
            </div>
        </div>

        <div class="thumbnail">
            <img src="static/social/background-bottom.png" alt="" style="margin:auto; height: 71vh; width: auto">          
        </div>
        
        <!-- <div class="d-flex align-items-center">
            <img
                height=150
                class="border rounded shadow"
                :src="avatar"
            >
            </img>
            <div v-if="profile" class="p-3">
                [[ profile.text ]]
            </div>
            <div v-else class="p-3 text-secondary">
                Profile text
            </div>
        </div>

        <div class='h5 mt-3 pt-2'>
            <div v-if="user.username == view">
                Your Messages
            </div>
            <div v-else>
                [[view]]'s Messages
            </div>
        </div>

        <div class="mb-3">
            {% csrf_token %}
            <div class="form-group">
                <div class='mb-2 mt-1'>
                    Type here to leave a message:
                </div>
                <textarea v-model="message" class='form-control' name='text' cols='50' rows='3'></textarea>
            </div>
            <div class="form-group mt-3">
                Public
                    <input v-model="public" value="yes" type='radio' class='pm_class ms-1 me-2' name='pm'>
                Private
                    <input v-model="public" value="no" type='radio' class='pm_class ms-1 me-4' name='pm'>
                <input type='hidden' name='recip' :value='view'>
                <button
                    class="btn btn-primary btn-sm"
                    @click="postMessage2"
                    :disabled="!message"
                >
                    Post Message
                </button>
            </div>
        </div>

        <div v-for="message in messages" class="my-1">
            [[ message.time]]
            <a :href="`{% url 'social:messages' %}?view=${message.sender}`">
                [[ message.sender ]]
            </a>
            <span v-if="message.public">
                wrote:
            </span>
            <span v-else class="whisper">
                whispered:
            </span>
            [[ message.text ]]
            <button
                v-if="(message.sender == user.username) || (message.recip == user.username)"
                @click="deleteMessage2(message)"
                class="btn btn-sm btn-danger border remove-btn ml-2"
            >
                <i class="far fa-trash-alt"></i>
            </button>
        </div> -->

    </div>
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/vue@next"></script>
<script>
    const app = Vue.createApp({
        delimiters: ["[[", "]]"],
        data() {
            return {
                ...{{vue_data|safe}},
                message: "",
                public: "yes",

            }
        },
        mounted() {
            $("#app").show();
        },
        methods: {
            postMessage1() {
                // POST new message using jQuery $.ajax
                let app = this;
                $.ajax({
                    method: "POST",
                    url: `{% url 'social:messages api' %}?view=${this.view}`,
                    body: {
                        message: this.message,
                        public: this.public,
                        recip: this.view,
                        text: this.message,
                    },
                    headers : {
                        "X-CSRFToken" : $("[name=csrfmiddlewaretoken]").val(),
                    },
                    success(data) {
                        app.messages = data.messages;
                        app.message = "";
                        app.public = "yes";
                    }
                })
            },
            postMessage2() {
                // POST new message using fetch API
                let app = this;
                formData = new FormData();
                formData.append('message', this.message);
                formData.append('public', this.public);
                formData.append('recip', this.view);
                formData.append('text', this.message);

                fetch(`{% url 'social:messages api' %}?view=${this.view}`, {
                    method: "POST",
                    body: formData,
                    headers : { "X-CSRFToken" : $("[name=csrfmiddlewaretoken]").val() },
                })
                .then(response => response.json())
                .then(data => {
                    app.messages = data.messages;
                    app.message = "";
                    app.public = "0";
                })
            },
            deleteMessage1(message) {
                // DELETE message using jQuery $.ajax
                let app = this;
                $.ajax({
                    method: "DELETE",
                    url: "{% url 'social:message api' 0 %}".replace("0", message.id),
                    headers : { "X-CSRFToken" : $("[name=csrfmiddlewaretoken]").val() },
                    success() {
                        app.messages = app.messages.filter(m => m.id != message.id);
                    },
                    error() {
                        alert("Deleting messsage failed");
                    }
                })
            },
            deleteMessage2(message) {
                // DELETE message using fetch API
                let app = this;
                fetch("{% url 'social:message api' 0 %}".replace("0", message.id), {
                    method: "DELETE",
                    headers : { "X-CSRFToken" : $("[name=csrfmiddlewaretoken]").val() },
                }).then(response => {
                    if (response.ok) 
                        app.messages = app.messages.filter(m => m.id != message.id);
                    else 
                        alert("Deleting messsage failed");
                })
            }
        },
        computed: {
            avatar() {
                if (this.profile && this.profile.image) 
                    return this.profile.image
                return "{% static 'social/profile-image.jpg' %}"
            }
        }
    })
    const vm = app.mount('#app')
</script>
{% endblock %}

social/templates/social/pages/member.html
{% extends "social/base.html" %}

{% block content %}
    <div>
        <h3>
            {{ greeting }} Profile
        </h3>
        {% if profile %}
            {% if profile.image %}
            <img height=150 src='{{profile.image.url}}'></img>
            {% endif %}
            {{ profile.text }}
        {% endif %}
        <a class='button' href="{% url 'social:messages' %}?view={{ view_user }}">View {{ greeting }} messages</a>
    </div>
{% endblock %}

social/templates/social/pages/profile.html
{% extends "social/base.html" %}
{% load static %}

{% block content %}
    <div class='h3 mt-4 text-center'>
        My Profile
    </div>
    {% include 'social/components/profile.html' %}
    <div class='h5 mt-4'>
        Edit profile and/or click on image to update
    </div>
    <form id='upload_form' method='POST' action="{% url 'social:profile' %}" enctype='multipart/form-data'>
        <div class='form-group'>
            {% csrf_token %}
            <textarea class="form-control" name='text' rows='4'>{{ profile.text }}</textarea>
            <input type="file" id="img_file" style="display:none;">
            <button type='submit' class="btn btn-primary mt-3">Save</button>
        </div>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        $(function () {
            // connecting click on profile image with click on upload file button
            $('#profile-img').click(function() {
                console.log('Uploading image...')
                $("#img_file").click()
            });

            $('#img_file').change(function uploadFile() {
                var formdata = new FormData()
                var file = document.getElementById('img_file').files[0]
                formdata.append('img_file', file)
                formdata.append('csrfmiddlewaretoken', $('input[name=csrfmiddlewaretoken]').val())
                $.ajax({
                    type : 'POST',
                    url  : "{% url 'social:uploadimage' %}",
                    data : formdata,
                    success: function(data) {
                        $('#profile-img').attr("src",data);
                    },
                    processData : false,
                    contentType : false,
                })
            })
        })
    </script>
{% endblock %}